---
openapi: 3.0.1
info:
  title: API V1
  version: v1
host: https://localhost:3000
paths:
  "/products":
    get:
      summary: Index products
      responses:
        '200':
          description: show products
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/product"
  "/products/{id}":
    get:
      summary: Show product
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: show product
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/product"
        '404':
          description: product not found
  "/carts":
    get:
      summary: Index carts
      responses:
        '200':
          description: show carts
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/cart"
  "/carts/{id}":
    get:
      summary: Show cart
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: show cart
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/cart"
        '404':
          description: cart not found
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: http://localhost:3000
components:
  schemas:
    product:
      type: object
      properties:
        id:
          type: number
          example: 1
        name:
          type: string
          example: apples
        brand:
          type: string
          example: Trader Joes
        price:
          type: number
          format: float
          example: 2.99
      required:
      - id
      - name
      - brand
      - price
    cart_product:
      type: object
      properties:
        product:
          "$ref": "#/components/schemas/product"
        quantity:
          type: number
          example: 5
      required:
      - product
      - quantity
    cart:
      type: object
      properties:
        id:
          type: number
          example: 1
        cart_products:
          type: array
          items:
            "$ref": "#/components/schemas/cart_product"
      required:
      - id
      - cart_products
