---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/products":
    get:
      summary: Show first ten products
      responses:
        '200':
          description: products shown
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  name:
                    type: string
                    example: apples
                  price:
                    type: number
                    format: float
                    example: 2.99
                required:
                - id
                - name
                - price
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: http://localhost:3000
