---
openapi: 3.0.1
info:
  title: API V1
  version: v1
host: https://localhost:3000
paths:
  "/carts":
    get:
      summary: Index carts
      tags:
      - Cart
      responses:
        '200':
          description: show carts
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/cart"
  "/carts/{id}":
    get:
      summary: Show cart
      tags:
      - Cart
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: show cart
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/cart"
        '404':
          description: cart not found
  "/products":
    get:
      summary: Index products
      tags:
      - Products
      responses:
        '200':
          description: show products
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/product"
  "/products/{id}":
    get:
      summary: Show product
      tags:
      - Products
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: show product
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/product"
        '404':
          description: product not found
  "/products/{id}/create_promotion":
    post:
      summary: Create a promotion
      tags:
      - Products
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: creates the promotion
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                discount:
                  type: float
                  example: 1
                discount_type:
                  type: string
                  enum:
                  - flat
                  - percentage
                  - b1g1free
                  example: flat
                start_time:
                  type: datetime
                  example: '2025-02-01T02:05:38+00:00'
                end_time:
                  type: datetime
                  example: '2026-03-02T02:05:38+00:00'
              required:
              - discount_type
              - discount
              - start_time
              - end_time
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: http://localhost:3000
components:
  schemas:
    product:
      type: object
      properties:
        id:
          type: number
          example: 1
        name:
          type: string
          example: apples
        brand:
          type: string
          example: Trader Joes
        price:
          type: number
          format: float
          example: 2.99
      required:
      - id
      - name
      - brand
      - price
    cart_product:
      type: object
      properties:
        product:
          "$ref": "#/components/schemas/product"
        quantity:
          type: number
          example: 5
      required:
      - product
      - quantity
    cart:
      type: object
      properties:
        id:
          type: number
          example: 1
        total:
          type: number
          example: 2.99
        discounted_total:
          type: number
          example: 2.99
        cart_products:
          type: array
          items:
            "$ref": "#/components/schemas/cart_product"
      required:
      - id
      - cart_products
